### ISSUE TITLE
run str_to_midi.py error

### ISSUE THREAD

**Issue by cendelian** [briansemrau/MIDI-LLM-tokenizer#1]
when I run str_to_midi.py. the error occur:

```
  File "/xxxxxxxxxxxxxxxxxxxxxx/MIDI-LLM-tokenizer/midi_util.py", line 93, in from_json
    return cls(**config)
TypeError: VocabConfig.__init__() missing 1 required positional argument: 'velocity_bins_override'
```

could you help me? what error it is and how to solve it?

**Comment by guangyusong** [comment]
This fixed it for me:

1. Delete this line:
```
    velocity_bins_override: Optional[List[int]]
```

2. Add this at the end:

```
    velocity_bins_override: Optional[List[int]] = None
```

See screenshot:

<img width="1125" alt="Screenshot 2023-07-19 at 12 57 32 AM" src="https://github.com/briansemrau/MIDI-LLM-tokenizer/assets/15316444/c0145fc7-7b74-409e-8df0-e97ff514c7a5">

**Comment by cendelian** [comment]
> 

thanks， I use vocab_config_v2_wip.json is also OK!!

**Comment by briansemrau** [comment]
I wouldn't recommend using the WIP vocab config. It won't work with any existing models

**Comment by briansemrau** [comment]
Fixed by https://github.com/briansemrau/MIDI-LLM-tokenizer/commit/734d081c9b56ebf77d52cff8612a3e5451b3086a
